Repository TGSAI/mdio-python, pull requests merged in 2022-09, with the labels that each got.

#41 Reduce automatic dependency checking interval
  .github/dependabot.yml
Labels: ci

#47 Variable levels of ZFP compression example in docs
  .pre-commit-config.yaml
  docs/index.md
  docs/notebooks/compression.ipynb
Labels: documentation

#51 Don't fail when EBCDIC decoding has an error.
  src/mdio/segy/parsers.py
Labels: bug

#52 Use dimension separator in arrays instead of `FSStore`
  .gitignore
  src/mdio/api/io_utils.py
  src/mdio/converters/segy.py
  src/mdio/segy/blocked_io.py
  tests/unit/conftest.py
Labels: bug

#54 Minor release v0.2.0
  pyproject.toml
Labels: breaking

#56 Pass package version to CLI command explicitly
  src/mdio/__main__.py
  tests/test_main.py
Labels: bug

#57 Update `.gitignore` for cached files and PyCharm project files
  .gitignore
Labels: ci

#30 Update `pyproject.toml` for Poetry 1.2
  pyproject.toml
Labels: build

#62 Make `storage_options` consistent with fsspec to be able to pass local cache directory
  src/mdio/api/io_utils.py
  src/mdio/segy/creation.py
  tests/unit/conftest.py
  tests/unit/test_accessor.py
Labels: enhancement

#66 Add cloud service provider connection string documentation
  README.md
  docs/usage.md
Labels: documentation

#67 Add markdown extension for trailing whitespace fix pre-commit hook
  .pre-commit-config.yaml
  docs/usage.md
Labels: ci
