Repository TGSAI/mdio-python, pull requests merged in 2023-06, with the labels that each got.

#213 Adds greater shot ingestions flexibility
  .flake8
  .gitignore
  poetry.lock
  src/mdio/commands/segy.py
  src/mdio/converters/segy.py
  src/mdio/segy/_workers.py
  src/mdio/segy/exceptions.py
  src/mdio/segy/geometry.py
  src/mdio/segy/parsers.py
  src/mdio/segy/utilities.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_segy_import_export.py
  tests/unit/test_segy_grid_overrides.py
Labels: enhancement

#227 Upgrade .gitignore and add more patterns
  .gitignore
Labels: refactoring

#228 Downgrade `furo` because `myst_nb` conflict (`sphinx<6')
  docs/requirements.txt
Labels: dependencies

#231 Rename `shot` Key in Grid Overrides to `shot_point`
  src/mdio/segy/geometry.py
  tests/integration/test_segy_import_export.py
  tests/unit/test_segy_grid_overrides.py
Labels: enhancement
