Repository TGSAI/mdio-python, pull requests merged in 2023-08, with the labels that each got.

#257 Cast `coord_to_index` return type to `uint32` for larger ranges
  src/mdio/api/accessor.py
Labels: bug

#246 Add QC for SEG-Y ingestion based on trace density.
  src/mdio/converters/segy.py
Labels: enhancement

#248 Support for Seismic Data Ingestion Without Dimension-Specific Indexing
  poetry.lock
  src/mdio/commands/segy.py
  src/mdio/converters/segy.py
  src/mdio/segy/geometry.py
  src/mdio/segy/parsers.py
  src/mdio/segy/utilities.py
  tests/integration/conftest.py
  tests/integration/test_segy_import_export.py
  tests/unit/test_segy_grid_overrides.py
Labels: enhancement

#260 Drop Python 3.8 Support to Enable Newer Dependencies
  .github/workflows/tests.yml
  noxfile.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#261 Update Docs Dependencies: `sphinx`, `sphinx-click`, `myst-parser`, `myst-nb`, `furo`.
  docs/requirements.txt
  noxfile.py
  poetry.lock
  pyproject.toml
Labels: ci, dependencies

#263 Update runtime dependency versions to latest: `dask`, `tqdm`, `click`, `zarr`, `numba`, `segyio`, `distributed`
  poetry.lock
  pyproject.toml
Labels: dependencies

#264 Update development dependencies to latest (linting, tests, etc.)
  poetry.lock
  pyproject.toml
  src/mdio/api/accessor.py
  src/mdio/segy/helpers_segy.py
  tests/unit/test_segy_grid_overrides.py
Labels: dependencies

#262 Update CI/CD dependency versions to latest
  .github/workflows/constraints-poetry.txt
  .github/workflows/constraints.txt
  .github/workflows/labeler.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: ci
