Repository TGSAI/mdio-python, pull requests merged in 2024-03, with the labels that each got.

#362 Refactor the CLI dynamic command resolution
  .github/workflows/constraints-poetry.txt
  .github/workflows/constraints.txt
  poetry.lock
  src/mdio/__main__.py
Labels: refactoring

#360 Update Coverage GitHub Action to v4 and Add Token
  .github/workflows/tests.yml
Labels: ci

#363 Update Numba 0.59 from experimental to stable
  poetry.lock
  pyproject.toml
Labels: dependencies

#364 New CLI Options
  .gitignore
  docs/usage.md
  noxfile.py
  poetry.lock
  pyproject.toml
  src/mdio/__main__.py
  src/mdio/commands/copy.py
  src/mdio/commands/info.py
  src/mdio/commands/segy.py
  tests/conftest.py
  tests/test_main.py
Labels: enhancement

#366 Add notice to Readme
  README.md
Labels: documentation

#338 AutoShotWrap grid override
  .devcontainer/Dockerfile
  src/mdio/converters/segy.py
  src/mdio/segy/geometry.py
  tests/integration/conftest.py
  tests/integration/test_segy_import_export.py
Labels: enhancement

#368 Function to rechunk single variables or batch variables from existing MDIO
  docs/index.md
  docs/notebooks/rechunking.ipynb
  docs/reference.md
  src/mdio/api/accessor.py
  src/mdio/api/convenience.py
Labels: enhancement

#371 Add access pattern info to `mdio info` command
  src/mdio/commands/info.py
Labels: enhancement
