Repository TGSAI/mdio-python, pull requests merged in 2025-07, with the labels that each got.

#567 [v1] Update dependencies to latest
  .github/workflows/tests.yml
  pyproject.toml
  src/mdio/schemas/compressors.py
  uv.lock
Labels: dependencies

#568 Implement MDIO Dataset builder to create in-memory instance of schemas.v1.dataset.Dataset
  src/mdio/schemas/v1/dataset_builder.py
  tests/unit/v1/__init__.py
  tests/unit/v1/helpers.py
  tests/unit/v1/test_dataset_builder_add_coordinate.py
  tests/unit/v1/test_dataset_builder_add_dimension.py
  tests/unit/v1/test_dataset_builder_add_variable.py
  tests/unit/v1/test_dataset_builder_build.py
  tests/unit/v1/test_dataset_builder_helpers.py
Labels: enhancement, v1

#572 Bump zarr version to `>=3.1.0`
  pyproject.toml
  uv.lock
Labels: dependencies

#575 Refactor SEG-Y ingestion workers to create new `SegyFile` instances instead of passing from main process
  src/mdio/segy/_workers.py
  src/mdio/segy/blocked_io.py
  src/mdio/segy/parsers.py
Labels: refactoring

#573 MDIO v1 Templates and Template Registry
  docs/index.md
  docs/template_registry.md
  src/mdio/schemas/v1/templates/abstract_dataset_template.py
  src/mdio/schemas/v1/templates/seismic_2d_poststack.py
  src/mdio/schemas/v1/templates/seismic_3d_poststack.py
  src/mdio/schemas/v1/templates/seismic_3d_prestack_cdp.py
  src/mdio/schemas/v1/templates/seismic_3d_prestack_shot.py
  src/mdio/schemas/v1/templates/template_registry.py
  tests/unit/v1/helpers.py
  tests/unit/v1/templates/test_seismic_2d_poststack.py
  tests/unit/v1/templates/test_seismic_3d_poststack.py
  tests/unit/v1/templates/test_seismic_3d_prestack_cdp.py
  tests/unit/v1/templates/test_seismic_3d_prestack_shot.py
  tests/unit/v1/templates/test_seismic_templates.py
  tests/unit/v1/templates/test_template_registry.py
  tests/unit/v1/test_dataset_builder_build.py
  tests/unit/v1/test_dataset_serializer.py
Labels: enhancement, v1
