Repository TGSAI/mdio-python, pull requests merged in 2025-09, with the labels that each got.

#632 v1 implementation of AutoChannelWrap grid override
  src/mdio/converters/segy.py
  src/mdio/schemas/v1/templates/abstract_dataset_template.py
  tests/integration/conftest.py
  tests/integration/test_segy_import_export.py
  tests/integration/test_segy_import_export_masked.py
Labels: v1

#630 Move to Zarr v3 as default for on disk storage format
  pyproject.toml
  src/mdio/__init__.py
  src/mdio/api/__init__.py
  src/mdio/api/accessor.py
  src/mdio/api/convenience.py
  src/mdio/api/io.py
  src/mdio/api/io_utils.py
  src/mdio/api/opener.py
  src/mdio/constants.py
  src/mdio/converters/__init__.py
  src/mdio/converters/mdio.py
  src/mdio/converters/numpy.py
  src/mdio/converters/segy.py
  src/mdio/core/dimension.py
  src/mdio/core/factory.py
  src/mdio/core/grid.py
  src/mdio/core/serialization.py
  src/mdio/core/storage_location.py
  src/mdio/schemas/chunk_grid.py
  src/mdio/schemas/compressors.py
  src/mdio/schemas/v0/__init__.py
  src/mdio/schemas/v0/dataset.py
  src/mdio/schemas/v1/dataset_builder.py
  src/mdio/schemas/v1/dataset_serializer.py
  src/mdio/schemas/v1/templates/abstract_dataset_template.py
  src/mdio/schemas/v1/templates/seismic_2d_poststack.py
  src/mdio/schemas/v1/templates/seismic_2d_prestack_cdp.py
  src/mdio/schemas/v1/templates/seismic_2d_prestack_shot.py
  src/mdio/schemas/v1/templates/seismic_3d_poststack.py
  src/mdio/schemas/v1/templates/seismic_3d_prestack_cdp.py
  src/mdio/schemas/v1/templates/seismic_3d_prestack_coca.py
  src/mdio/schemas/v1/templates/seismic_3d_prestack_shot.py
  src/mdio/segy/_workers.py
  src/mdio/segy/blocked_io.py
  src/mdio/segy/creation.py
  tests/integration/test_numpy_ingest.py
  tests/integration/test_segy_import_export.py
  tests/integration/test_segy_import_export_masked.py
  tests/unit/conftest.py
  tests/unit/test_accessor.py
  tests/unit/test_convenience.py
  tests/unit/test_dimension.py
  tests/unit/test_factory.py
  tests/unit/test_schema.py
  tests/unit/test_serialization.py
  tests/unit/v1/converters/test_type_converter.py
  tests/unit/v1/core/test_storage_location.py
  tests/unit/v1/helpers.py
  tests/unit/v1/templates/test_seismic_2d_poststack.py
  tests/unit/v1/templates/test_seismic_3d_poststack.py
  tests/unit/v1/templates/test_seismic_3d_prestack_cdp.py
  tests/unit/v1/templates/test_seismic_3d_prestack_coca.py
  tests/unit/v1/templates/test_seismic_3d_prestack_shot.py
  tests/unit/v1/test_dataset_builder_add_coordinate.py
  tests/unit/v1/test_dataset_builder_add_variable.py
  tests/unit/v1/test_dataset_builder_build.py
  tests/unit/v1/test_dataset_serializer.py
  uv.lock
Labels: v1

#637 Fix cloud I/O problem
  src/mdio/converters/segy.py
Labels: v1

#640 Allow legacy Zarr (v2) support
  src/mdio/api/io.py
  src/mdio/constants.py
  src/mdio/core/grid.py
  src/mdio/core/utils_write.py
  src/mdio/schemas/v1/dataset_serializer.py
  src/mdio/segy/blocked_io.py
Labels: v1

#647 Disable unimplemented tests
  pyproject.toml
  tests/integration/test_segy_import_export.py
  tests/test_main.py
Labels: v1

#648 Resolve header packing and rename DatasetBuilder's `header` kwarg to `header_dtype` for clarity.
  src/mdio/builder/templates/abstract_dataset_template.py
  src/mdio/converters/segy.py
  tests/unit/v1/templates/test_seismic_2d_poststack.py
  tests/unit/v1/templates/test_seismic_2d_prestack_cdp.py
  tests/unit/v1/templates/test_seismic_2d_prestack_shot.py
  tests/unit/v1/templates/test_seismic_3d_poststack.py
  tests/unit/v1/templates/test_seismic_3d_prestack_cdp.py
  tests/unit/v1/templates/test_seismic_3d_prestack_coca.py
  tests/unit/v1/templates/test_seismic_3d_prestack_shot.py
Labels: v1

#650 Update README.md with v1 news and clean up some functionality lists.
  README.md
Labels: documentation

#651 Unwrap long(ish) lines in noxfile thanks to new character limit
  noxfile.py
Labels: refactoring

#671 Bundle LICENSE with source tarball
  pyproject.toml
Labels: build

#672 Enable execution of quickstart for better rendering
  docs/requirements.txt
  docs/tutorials/quickstart.ipynb
  noxfile.py
  pyproject.toml
  uv.lock
Labels: documentation

#679 Fix statistics calculations
  src/mdio/segy/_workers.py
  tests/integration/test_segy_roundtrip_teapot.py
Labels: bug

#678 Update `zarr` minimum version to `3.1.3`
  pyproject.toml
  uv.lock
Labels: dependencies
